# Generated by Django 4.0.4 on 2022-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
