# Generated by Django 4.0.4 on 2022-05-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest_essential_india', '0002_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
